### ISSUE TITLE
Lovely product! Do you think it's a good idea to generate grid CSS code as well ?

### ISSUE THREAD

**Issue by woraperth** [Angelmmiguel/graaf#2]
Hi Angel,

I love your idea about custom grid overlay. It would come in handy for every frontend developers who do PSD to HTML/CSS frequently.

Have you considered adding grid CSS code (something like .col-md, .col-lg) ? It would be the one stop tool for all needs about grid !

Cheers,
Woratana

**Comment by Angelmmiguel** [comment]
Hello Woratana,

Thank you! I'm glad that you liked the project :)

That's an idea I was thinking during the weekend. It's a cool idea and I want to investigate more about grids. There are a lot of strategies to generate grids like `float` or `flexbox`.

However, I'm not sure if I will publish the real grid code in this project. I'd rather create another repository. The main reason is this is not a CDN. The Graaf overlay generator is deployed in a custom server, so It's okey for development but not for production. I want to avoid people to use it in a wrong way, I want your projects run quickly ;)

The short answer is **yes**, I'll create a real grid generator too.

Thanks for your suggestion, I'll keep you in touch about this.

Regards,
Ángel

**Comment by Angelmmiguel** [comment]
I'm going to close this issue. Please, feel free to open another one if you have other questions :)
