### ISSUE TITLE
Add to Bower

### ISSUE THREAD

**Issue by dlewand691** [Angelmmiguel/graaf#3]
Would be nice to have a Bower version to quickly add to projects. Thank you!

**Comment by Angelmmiguel** [comment]
Good idea! I'll add the library to Bower. 

Meanwhile, you can get it from [npm](https://www.npmjs.com/package/graaf). I didn't promote this way to include Graaf because I want to add some documentation about the mixin and how using it.

**Comment by Angelmmiguel** [comment]
Now, Graaf is available on Bower :)

```
$ bower info graaf#0.2.3
bower graaf#0.2.3   cached https://github.com/Angelmmiguel/graaf.git#0.2.3
bower graaf#0.2.3   validate 0.2.3 against https://github.com/Angelmmiguel/graaf.git#0.2.3
```

**Comment by Angelmmiguel** [comment]
More information in the [bower.json](https://github.com/Angelmmiguel/graaf/blob/master/bower.json) file.
