### ISSUE TITLE
Start and end with gutter on far left and right sides

### ISSUE THREAD

**Issue by dlewand691** [Angelmmiguel/graaf#5]
Rather than starting and ending with a full column, can the grid start with the gutter instead? I'm using Foundation and would be great to match closer to their grid structure.

**Comment by Angelmmiguel** [comment]
Some grids split the gutter in _inner_ and _outer_. To make Graaf simple, I reduced the common grid parameters to three: width, columns and gutter. I'd rather not add more parameters to the grid overlays.

Also, the content should be aligned with the columns. So the outer gutter shouldn't be important. For grid systems that uses this double gutter, I sum them and ignore one.

Thanks for your suggestion, but I won't add new parameters to the grid overlays for the moment.

**PS**: I'm going to add `Foundation` grid in the following versions. Stay tuned ;)
